const fallback = [
 {title:'Design, construction and finite element analysis of a hexacopter for precision agriculture applications',year:2024,authors:'M.E. Gutierrez-Rivera Â· J.Y. Rumbo-Morales',venue:'Modelling',url:'https://www.mdpi.com/2673-3951/5/3/64',tags:['FEA','Agriculture'],abstract:'This study presents the design and construction of a hexacopter for precision agriculture. Finite element analysis evaluates the mechanical response of its structural components and validates the design for real-world flight loads.'},
 {title:'Design and Validation of a 3D-Printed Drone Chassis Model through Static and Transient Nonlinear FEM Analyses',year:2025,authors:'B.M. Al-Hadithi Â· S. Alcon Flores',venue:'Drones',url:'https://www.mdpi.com/2504-446X/9/11/789',tags:['FEM','3D printing'],abstract:'A 3D-printed drone chassis is evaluated using static and transient nonlinear finite element analysis, then checked experimentally. Results connect additive manufacturing choices with structural performance.'},
 {title:'Generative design, simulation, and 3D printing of the quadcopter drone frame',year:2025,authors:'V. Andries Â· S.M. Zaharia',venue:'Applied Sciences',url:'https://www.mdpi.com/2076-3417/15/17/9647',tags:['Generative design','Optimization'],abstract:'The paper combines generative design with finite element analysis and computational fluid dynamics to create a lightweight quadcopter frame. The redesigned frame is validated through simulation and printing.'},
 {title:'Design and analysis of a topology-optimized quadcopter drone frame',year:2024,authors:'B. Bay Â· M. Eryildiz',venue:'Gazi University Journal',url:'https://dergipark.org.tr/en/pub/gujsc/issue/85642/1316791',tags:['Topology optimization','FEA'],abstract:'Topology optimization is applied during the initial drone-frame design phase to identify an efficient shape and size. The approach targets lower mass while maintaining strength and stiffness.'},
 {title:'Sustainable valorization of kenaf fiber waste in polymer composites for drone arm structure',year:2025,authors:'N.K. Chandran Â· M.T.H. Sultan Â· F.S. Shahar',venue:'Journal of Composites Science',url:'https://www.mdpi.com/2504-477X/9/9/505',tags:['Composite materials','Sustainability'],abstract:'This work investigates kenaf-fiber polymer composites for quadcopter arms using finite element analysis. It compares structural behavior and explores a lower-impact alternative to conventional materials.'},
 {title:'A payload based detail study on design and simulation of hexacopter drone',year:2024,authors:'S. Shelare Â· P. Belkhode Â· K.C. Nikam',venue:'International Journal on Interactive Design',url:'https://link.springer.com/article/10.1007/s12008-023-01269-w',tags:['Payload','Simulation'],abstract:'A hexacopter design is studied around payload capacity, with finite element analysis used to assess the structural response of the selected configuration under operational conditions.'},
 {title:'Drone frame optimization via simulation and 3D printing',year:2025,authors:'F. Kateb Â· A. Haseeb Â· S. Misbah-Un-Noor',venue:'Computers',url:'https://www.mdpi.com/2073-431X/14/8/328',tags:['Optimization','3D printing'],abstract:'A lightweight drone frame is optimized through CAD, finite element analysis, CFD and 3D printing. The integrated workflow evaluates both structural durability and practical manufacturability.'},
 {title:'Advanced optimization of drone frame design through generative design techniques',year:2025,authors:'M. Darsin Â· W.J. Pamungkas Â· S.N.H. Syuhri',venue:'Journal of Mechanical Engineering',url:'https://link.springer.com/article/10.1007/s12206-024-1210-x',tags:['Generative design','Modal analysis'],abstract:'Candidate drone-frame designs are generated and tested through static and dynamic simulation. One optimized design demonstrates minimal displacement under a representative payload.'},
 {title:'Design, control, aerodynamic performances, and structural integrity of a compact ducted drone',year:2024,authors:'S.S. Jayakumar Â· I.P. Subramaniam',venue:'Scientific Reports',url:'https://www.nature.com/articles/s41598-024-54174-x',tags:['Aerodynamics','Structural integrity'],abstract:'The compact ducted drone is assessed across design, control and aerodynamic performance. Finite element analysis checks structural integrity under defined support and pressure conditions.'},
 {title:'Finite element analysis and experimental whiffletree testing of a small UAV composite wing',year:2025,authors:'A. Marta Â· F.A. Wandono Â· A. Nurrohmad',venue:'Aerospace Science and Technology',url:'https://www.sciencedirect.com/science/article/pii/S2588840425000277',tags:['UAV','Experimental validation'],abstract:'A small UAV composite wing is studied using finite element analysis alongside experimental whiffletree testing. The comparison offers a fuller picture of wing behavior and model accuracy.'},
 {title:'Effect of boundary condition on numerical study of UAV composite skin panels',year:2024,authors:'I.B. Wiranto Â· S.O. Saraswati Â· I.R. Alfikri',venue:'Mekanika',url:'https://jurnal.uns.ac.id/mekanika/article/view/77875',tags:['Composite','Impact loading'],abstract:'The study examines how boundary conditions affect numerical predictions for composite UAV skin panels under dynamic impact loading, providing guidance for more reliable simulation setups.'},
 {title:'Quadcopter unmanned aerial vehicle structural design using topology optimization',year:2024,authors:'L.A. Al-Haddad Â· A.A. Jaber Â· W. Giernacki',venue:'Designs',url:'https://www.mdpi.com/2411-9660/8/3/58',tags:['Topology optimization','Additive manufacturing'],abstract:'An integrated approach combines topology optimization, additive manufacturing and finite element analysis to reduce frame mass while preserving the stability and thrust-related requirements of a quadcopter.'}
];
let papers=[...fallback], saved=JSON.parse(localStorage.getItem('papertrail-saved')||'[]'), count=12;
const $=id=>document.getElementById(id); const currentYear=new Date().getFullYear();
for(let y=currentYear;y>=2018;y--){$('fromYear').insertAdjacentHTML('beforeend',`<option>${y}</option>`);$('toYear').insertAdjacentHTML('beforeend',`<option>${y}</option>`)} $('fromYear').value=2024;$('toYear').value=2026;
function summarize(p){return p.abstract||`This paper investigates ${p.title.toLowerCase()}, outlining its methods, evaluation approach, and implications for future research.`}
function render(list=papers){$('resultHeading').textContent=`${list.length} papers worth your time`;$('resultMeta').textContent=`${list.length} results Â· summaries generated from paper abstracts Â· ${list.some(p=>p.live)?'Live OpenAlex results':'Curated demo results'}`;$('results').innerHTML=list.map((p,i)=>`<article class="paper-card"><div class="paper-index">${String(i+1).padStart(2,'0')}</div><div><h3><a href="${p.url}" target="_blank" rel="noreferrer">${p.title}</a></h3><div class="paper-byline">${p.authors||'Authors not listed'} Â· ${p.venue||'Research paper'} Â· ${p.year||'n.d.'}</div><p class="paper-summary">${summarize(p)}</p><div>${(p.tags||['Research']).slice(0,3).map((t,j)=>`<span class="tag ${j===1?'orange':''}">${t}</span>`).join('')}</div></div><div class="card-actions"><button class="icon-btn ${saved.includes(p.url)?'saved':''}" data-save="${p.url}" title="Save paper">${saved.includes(p.url)?'â™¥':'â™¡'}</button><button class="icon-btn" onclick="window.open('${p.url}','_blank')" title="Open paper">â†—</button></div></article>`).join('')}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2400)}
async function search(){const topic=$('topicInput').value.trim();if(!topic)return; $('searchBtn').textContent='Searchingâ€¦';let live=[];try{const from=$('fromYear').value,to=$('toYear').value;const r=await fetch(`https://api.openalex.org/works?search=${encodeURIComponent(topic)}&filter=from_publication_date:${from}-01-01,to_publication_date:${to}-12-31&per-page=${count}&sort=relevance_score:desc`);const d=await r.json();live=(d.results||[]).filter(x=>x.title).map(x=>({title:x.title,year:x.publication_year,authors:(x.authorships||[]).slice(0,3).map(a=>a.author.display_name).join(' Â· '),venue:x.primary_location?.source?.display_name,url:x.primary_location?.landing_page_url||x.doi||x.open_access?.oa_url||`https://openalex.org/${x.id}`,abstract:x.abstract_inverted_index?Object.keys(x.abstract_inverted_index).sort((a,b)=>x.abstract_inverted_index[a][0]-x.abstract_inverted_index[b][0]).join(' '):'',tags:['OpenAlex',x.open_access?.is_oa?'Open access':'Research'],live:true}));}catch(e){}papers=live.length?live:fallback.filter(p=>p.title.toLowerCase().includes(topic.toLowerCase().split(' ')[0])||true).slice(0,count);$('searchBtn').innerHTML='Search papers <span>â†—</span>';render(papers);toast(live.length?`Found ${live.length} papers from OpenAlex`:'Showing curated results â€” live source unavailable')}
document.addEventListener('click',e=>{const save=e.target.closest('[data-save]');if(save){const url=save.dataset.save;saved=saved.includes(url)?saved.filter(x=>x!==url):[...saved,url];localStorage.setItem('papertrail-saved',JSON.stringify(saved));$('savedCount').textContent=saved.length;render();toast(saved.includes(url)?'Saved to your reading list':'Removed from saved')}});
$('searchBtn').onclick=search;$('increase').onclick=()=>{count=Math.min(50,count+1);$('countValue').textContent=count};$('decrease').onclick=()=>{count=Math.max(1,count-1);$('countValue').textContent=count};$('customBtn').onclick=()=>$('customFilters').classList.toggle('hidden');$('applyCustom').onclick=()=>{let k=$('keywordFilter').value.toLowerCase();papers=papers.filter(p=>!k||`${p.title} ${p.abstract}`.toLowerCase().includes(k));render(papers);toast('Custom filters applied')};$('sortSelect').onchange=e=>{papers.sort((a,b)=>e.target.value==='newest'?b.year-a.year:e.target.value==='citations'?b.year-a.year:0);render()};
document.querySelectorAll('.suggestion-chips button').forEach(b=>b.onclick=()=>{$('aiInput').value=b.dataset.prompt;sendAI()});function sendAI(){const q=$('aiInput').value.trim();if(!q)return;const thread=$('aiThread');thread.insertAdjacentHTML('beforeend',`<div class="user-message">${q}</div>`);let answer=q.toLowerCase().includes('gap')?'Across this set, the clearest opportunity is stronger experimental validation: many papers optimize or simulate frames, but fewer connect nonlinear FEA, manufacturing variation, and full-flight testing in one repeatable workflow.':q.toLowerCase().includes('practical')?'Start with the 3D-printed chassis and the whiffletree-tested composite wing. Together they cover a buildable workflow and an explicit simulation-to-experiment check.':'The set clusters around topology optimization, composite or additive materials, and simulation-to-test validation. The recurring pattern is mass reduction under payload constraints; the main difference is how convincingly each paper validates its model.';thread.insertAdjacentHTML('beforeend',`<div class="ai-message"><span class="mini-spark">âœ¦</span><p>${answer}</p></div>`);$('aiInput').value='';thread.scrollTop=thread.scrollHeight} $('aiSend').onclick=sendAI;$('aiInput').addEventListener('keydown',e=>{if(e.key==='Enter')sendAI()});
document.querySelectorAll('.nav-item').forEach(n=>n.onclick=()=>{document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));n.classList.add('active');$('viewLabel').textContent=n.textContent.trim().replace(/\d+$/,'');if(n.dataset.view==='saved'){const set=papers.filter(p=>saved.includes(p.url));$('emptyState').classList.toggle('hidden',set.length>0);$('results').classList.toggle('hidden',!set.length);if(set.length)render(set)}else{$('emptyState').classList.add('hidden');$('results').classList.remove('hidden');render(papers)}});$('savedCount').textContent=saved.length;render();

