const fallback = [
  {title:'Design, construction and finite element analysis of a hexacopter for precision agriculture applications',year:2024,authors:'M.E. Gutierrez-Rivera - J.Y. Rumbo-Morales',venue:'Modelling',url:'https://www.mdpi.com/2673-3951/5/3/64',tags:['FEA','Agriculture'],abstract:'This study presents the design and construction of a hexacopter for precision agriculture. Finite element analysis evaluates the mechanical response of its structural components and validates the design for real-world flight loads.'},
  {title:'Design and Validation of a 3D-Printed Drone Chassis Model through Static and Transient Nonlinear FEM Analyses',year:2025,authors:'B.M. Al-Hadithi - S. Alcon Flores',venue:'Drones',url:'https://www.mdpi.com/2504-446X/9/11/789',tags:['FEM','3D printing'],abstract:'A 3D-printed drone chassis is evaluated using static and transient nonlinear finite element analysis, then checked experimentally. Results connect additive manufacturing choices with structural performance.'},
  {title:'Generative design, simulation, and 3D printing of the quadcopter drone frame',year:2025,authors:'V. Andries - S.M. Zaharia',venue:'Applied Sciences',url:'https://www.mdpi.com/2076-3417/15/17/9647',tags:['Generative design','Optimization'],abstract:'The paper combines generative design with finite element analysis and computational fluid dynamics to create a lightweight quadcopter frame. The redesigned frame is validated through simulation and printing.'},
  {title:'Design and analysis of a topology-optimized quadcopter drone frame',year:2024,authors:'B. Bay - M. Eryildiz',venue:'Gazi University Journal',url:'https://dergipark.org.tr/en/pub/gujsc/issue/85642/1316791',tags:['Topology optimization','FEA'],abstract:'Topology optimization is applied during the initial drone-frame design phase to identify an efficient shape and size. The approach targets lower mass while maintaining strength and stiffness.'},
  {title:'Sustainable valorization of kenaf fiber waste in polymer composites for drone arm structure',year:2025,authors:'N.K. Chandran - M.T.H. Sultan - F.S. Shahar',venue:'Journal of Composites Science',url:'https://www.mdpi.com/2504-477X/9/9/505',tags:['Composite materials','Sustainability'],abstract:'This work investigates kenaf-fiber polymer composites for quadcopter arms using finite element analysis. It compares structural behavior and explores a lower-impact alternative to conventional materials.'},
  {title:'A payload based detail study on design and simulation of hexacopter drone',year:2024,authors:'S. Shelare - P. Belkhode - K.C. Nikam',venue:'International Journal on Interactive Design',url:'https://link.springer.com/article/10.1007/s12008-023-01269-w',tags:['Payload','Simulation'],abstract:'A hexacopter design is studied around payload capacity, with finite element analysis used to assess the structural response of the selected configuration under operational conditions.'},
  {title:'Drone frame optimization via simulation and 3D printing',year:2025,authors:'F. Kateb - A. Haseeb - S. Misbah-Un-Noor',venue:'Computers',url:'https://www.mdpi.com/2073-431X/14/8/328',tags:['Optimization','3D printing'],abstract:'A lightweight drone frame is optimized through CAD, finite element analysis, CFD and 3D printing. The integrated workflow evaluates both structural durability and practical manufacturability.'},
  {title:'Advanced optimization of drone frame design through generative design techniques',year:2025,authors:'M. Darsin - W.J. Pamungkas - S.N.H. Syuhri',venue:'Journal of Mechanical Engineering',url:'https://link.springer.com/article/10.1007/s12206-024-1210-x',tags:['Generative design','Modal analysis'],abstract:'Candidate drone-frame designs are generated and tested through static and dynamic simulation. One optimized design demonstrates minimal displacement under a representative payload.'},
  {title:'Design, control, aerodynamic performances, and structural integrity of a compact ducted drone',year:2024,authors:'S.S. Jayakumar - I.P. Subramaniam',venue:'Scientific Reports',url:'https://www.nature.com/articles/s41598-024-54174-x',tags:['Aerodynamics','Structural integrity'],abstract:'The compact ducted drone is assessed across design, control and aerodynamic performance. Finite element analysis checks structural integrity under defined support and pressure conditions.'},
  {title:'Finite element analysis and experimental whiffletree testing of a small UAV composite wing',year:2025,authors:'A. Marta - F.A. Wandono - A. Nurrohmad',venue:'Aerospace Science and Technology',url:'https://www.sciencedirect.com/science/article/pii/S2588840425000277',tags:['UAV','Experimental validation'],abstract:'A small UAV composite wing is studied using finite element analysis alongside experimental whiffletree testing. The comparison offers a fuller picture of wing behavior and model accuracy.'},
  {title:'Effect of boundary condition on numerical study of UAV composite skin panels',year:2024,authors:'I.B. Wiranto - S.O. Saraswati - I.R. Alfikri',venue:'Mekanika',url:'https://jurnal.uns.ac.id/mekanika/article/view/77875',tags:['Composite','Impact loading'],abstract:'The study examines how boundary conditions affect numerical predictions for composite UAV skin panels under dynamic impact loading, providing guidance for more reliable simulation setups.'},
  {title:'Quadcopter unmanned aerial vehicle structural design using topology optimization',year:2024,authors:'L.A. Al-Haddad - A.A. Jaber - W. Giernacki',venue:'Designs',url:'https://www.mdpi.com/2411-9660/8/3/58',tags:['Topology optimization','Additive manufacturing'],abstract:'An integrated approach combines topology optimization, additive manufacturing and finite element analysis to reduce frame mass while preserving the stability and thrust-related requirements of a quadcopter.'}
];
let papers=[...fallback], count=12;
const profileStoreKey='papertrail-profiles';
const activeProfileKey='papertrail-active-profile';
let profiles=JSON.parse(localStorage.getItem(profileStoreKey)||'[]');
if(!Array.isArray(profiles))profiles=[];
let activeProfileId=localStorage.getItem(activeProfileKey)||'';
let activeProfile=profiles.find(p=>p.id===activeProfileId)||profiles[0]||null;
if(activeProfile){activeProfileId=activeProfile.id;localStorage.setItem(activeProfileKey,activeProfileId)}
function profileDataKey(){return `papertrail-data-${activeProfileId}`}
function migrateLegacySaved(){const old=JSON.parse(localStorage.getItem('papertrail-saved')||'[]');return Array.isArray(old)?old.filter(url=>typeof url==='string').map(url=>fallback.find(p=>p.url===url)||{title:'Previously saved paper',authors:'Authors not listed',venue:'Saved paper',url,abstract:'This paper was saved before local profiles were added.'}):[]}
function loadProfileData(){const data=JSON.parse(localStorage.getItem(profileDataKey())||'{}');let items=Array.isArray(data.savedItems)?data.savedItems:[];return items.filter(p=>p&&p.url)}
let savedItems=loadProfileData(), saved=savedItems.map(p=>p.url);
function persistProfileData(){localStorage.setItem(profileDataKey(),JSON.stringify({savedItems,preferences:{topic:$('topicInput')?.value||'',fromYear:$('fromYear')?.value||'',toYear:$('toYear')?.value||''}}))}
function refreshProfileUi(){const name=activeProfile?.name||'Profile';$('profileBtn').textContent=(name.slice(0,2)||'P').toUpperCase();$('profileTitle').textContent=activeProfile?`${name}'s local profile`:'Choose your profile';$('profileName').value='';$('profileSelect').innerHTML='<option value="">Select an existing profile</option>'+profiles.map(p=>`<option value="${p.id}" ${p.id===activeProfileId?'selected':''}>${p.name}</option>`).join('');$('profileSave').textContent=activeProfile?'Create or switch profile':'Create profile'}
function openProfileModal(){$('profileModal').classList.remove('hidden');refreshProfileUi()}
function closeProfileModal(){$('profileModal').classList.add('hidden')}
const $=id=>document.getElementById(id); const currentYear=new Date().getFullYear();
for(let y=currentYear;y>=2018;y--){$('fromYear').insertAdjacentHTML('beforeend',`<option>${y}</option>`);$('toYear').insertAdjacentHTML('beforeend',`<option>${y}</option>`)} $('fromYear').value=2024;$('toYear').value=currentYear;
function summarize(p){return p.abstract||`This paper investigates ${p.title.toLowerCase()}, outlining its methods, evaluation approach, and implications for future research.`}
function render(list=papers){$('resultHeading').textContent=`${list.length} papers worth your time`;$('resultMeta').textContent=`${list.length} results - summaries generated from paper abstracts - ${list.some(p=>p.live)?'Live OpenAlex results':'Curated demo results'}`;$('results').innerHTML=list.map((p,i)=>`<article class="paper-card"><div class="paper-index">${String(i+1).padStart(2,'0')}</div><div><h3><a href="${p.url}" target="_blank" rel="noreferrer">${p.title}</a></h3><div class="paper-byline">${p.authors||'Authors not listed'} - ${p.venue||'Research paper'} - ${p.year||'n.d.'}</div><p class="paper-summary">${summarize(p)}</p><div>${(p.tags||['Research']).slice(0,3).map((t,j)=>`<span class="tag ${j===1?'orange':''}">${t}</span>`).join('')}</div></div><div class="card-actions"><button class="save-btn ${saved.includes(p.url)?'saved':''}" data-save="${p.url}">${saved.includes(p.url)?'Saved':'Save'}</button><button class="open-btn" onclick="window.open('${p.url}','_blank')">Open</button></div></article>`).join('')}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2400)}
async function search(){const topic=$('topicInput').value.trim();if(!topic)return;$('searchBtn').textContent='Searching...';let live=[];try{const from=$('fromYear').value,to=$('toYear').value;const r=await fetch(`https://api.openalex.org/works?search=${encodeURIComponent(topic)}&filter=from_publication_date:${from}-01-01,to_publication_date:${to}-12-31&per-page=${count}&sort=relevance_score:desc`);const d=await r.json();live=(d.results||[]).filter(x=>x.title).map(x=>({title:x.title,year:x.publication_year,authors:(x.authorships||[]).slice(0,3).map(a=>a.author.display_name).join(' - '),venue:x.primary_location?.source?.display_name,url:x.primary_location?.landing_page_url||x.doi||x.open_access?.oa_url||`https://openalex.org/${x.id}`,abstract:x.abstract_inverted_index?Object.keys(x.abstract_inverted_index).sort((a,b)=>x.abstract_inverted_index[a][0]-x.abstract_inverted_index[b][0]).join(' '):'',tags:['OpenAlex',x.open_access?.is_oa?'Open access':'Research'],live:true}));}catch(e){}papers=live.length?live:fallback.slice(0,count);$('searchBtn').textContent='Search papers';render(papers);toast(live.length?`Found ${live.length} papers from OpenAlex`:'Showing curated results - live source unavailable')}
function escapeHtml(value){return String(value||'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function exportPdf(){const rows=papers.map((p,i)=>`<tr><td>${i+1}</td><td><strong>${escapeHtml(p.title)}</strong><br><a href="${escapeHtml(p.url)}">Open paper</a></td><td>${escapeHtml(p.authors||'Authors not listed')}</td><td>${escapeHtml(summarize(p))}</td></tr>`).join('');const win=window.open('','_blank');if(!win){toast('Please allow pop-ups to export the PDF');return}win.document.write(`<!doctype html><html><head><title>Papertrail paper brief</title><style>body{font-family:Arial,sans-serif;color:#1e2421;padding:28px}h1{margin:0 0 6px}p{color:#66736a}table{border-collapse:collapse;width:100%;font-size:11px}th,td{border:1px solid #cfd8cf;padding:9px;vertical-align:top;text-align:left}th{background:#e8f0e6}td:first-child{width:28px}td:nth-child(2){width:27%}td:nth-child(3){width:20%}a{color:#365c45}@media print{button{display:none}}</style></head><body><h1>Papertrail - Paper brief</h1><p>${papers.length} papers currently shown. Use your browser print dialog and choose "Save as PDF".</p><table><thead><tr><th>#</th><th>Paper title</th><th>Authors</th><th>Brief</th></tr></thead><tbody>${rows}</tbody></table><script>window.onload=()=>window.print()<\/script></body></html>`);win.document.close();toast('Print dialog opened - choose Save as PDF')}
document.addEventListener('click',e=>{const save=e.target.closest('[data-save]');if(save){const url=save.dataset.save;const paper=papers.find(p=>p.url===url)||fallback.find(p=>p.url===url);if(saved.includes(url)){savedItems=savedItems.filter(p=>p.url!==url);saved=saved.filter(x=>x!==url)}else if(paper){savedItems=[...savedItems.filter(p=>p.url!==url),paper];saved=[...saved,url]}persistProfileData();localStorage.setItem('papertrail-saved',JSON.stringify(saved));$('savedCount').textContent=saved.length;render();toast(saved.includes(url)?'Saved to your reading list':'Removed from saved')}});
$('searchBtn').onclick=search;$('exportPdf').onclick=exportPdf;$('increase').onclick=()=>{count=Math.min(50,count+1);$('countValue').textContent=count};$('decrease').onclick=()=>{count=Math.max(1,count-1);$('countValue').textContent=count};$('customBtn').onclick=()=>$('customFilters').classList.toggle('hidden');$('applyCustom').onclick=()=>{let k=$('keywordFilter').value.toLowerCase();papers=papers.filter(p=>!k||`${p.title} ${p.abstract}`.toLowerCase().includes(k));render(papers);toast('Custom filters applied')};$('sortSelect').onchange=e=>{papers.sort((a,b)=>e.target.value==='newest'?b.year-a.year:e.target.value==='citations'?b.year-a.year:0);render()};
document.querySelectorAll('.suggestion-chips button').forEach(b=>b.onclick=()=>{$('aiInput').value=b.dataset.prompt;sendAI()});function sendAI(){const q=$('aiInput').value.trim();if(!q)return;const thread=$('aiThread');thread.insertAdjacentHTML('beforeend',`<div class="user-message">${escapeHtml(q)}</div>`);let answer=q.toLowerCase().includes('gap')?'Across this set, the clearest opportunity is stronger experimental validation: many papers optimize or simulate frames, but fewer connect nonlinear FEA, manufacturing variation, and full-flight testing in one repeatable workflow.':q.toLowerCase().includes('practical')?'Start with the 3D-printed chassis and the whiffletree-tested composite wing. Together they cover a buildable workflow and an explicit simulation-to-experiment check.':'The set clusters around topology optimization, composite or additive materials, and simulation-to-test validation. The recurring pattern is mass reduction under payload constraints; the main difference is how convincingly each paper validates its model.';thread.insertAdjacentHTML('beforeend',`<div class="ai-message"><span class="mini-spark">AI</span><p>${answer}</p></div>`);$('aiInput').value='';thread.scrollTop=thread.scrollHeight} $('aiSend').onclick=sendAI;$('aiInput').addEventListener('keydown',e=>{if(e.key==='Enter')sendAI()});
document.querySelectorAll('.nav-item').forEach(n=>n.onclick=()=>{document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));n.classList.add('active');$('viewLabel').textContent=n.textContent.trim().replace(/\d+$/,'');if(n.dataset.view==='saved'){const set=savedItems;$('emptyState').classList.toggle('hidden',set.length>0);$('results').classList.toggle('hidden',!set.length);if(set.length)render(set)}else{$('emptyState').classList.add('hidden');$('results').classList.remove('hidden');render(papers)}});$('savedCount').textContent=saved.length;render();
$('profileBtn').onclick=openProfileModal;$('profileClose').onclick=closeProfileModal;$('profileSave').onclick=()=>{const selected=$('profileSelect').value;const typed=$('profileName').value.trim();if(selected){activeProfileId=selected;activeProfile=profiles.find(p=>p.id===selected)}else if(typed){const id=typed.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||`profile-${Date.now()}`;activeProfile={id,name:typed};profiles=[...profiles.filter(p=>p.id!==id),activeProfile];activeProfileId=id;localStorage.setItem(profileStoreKey,JSON.stringify(profiles))}else{toast('Enter a profile name or choose an existing profile');return}localStorage.setItem(activeProfileKey,activeProfileId);savedItems=loadProfileData();if(!savedItems.length&&profiles.length===1){const old=JSON.parse(localStorage.getItem('papertrail-saved')||'[]');savedItems=fallback.filter(p=>Array.isArray(old)&&old.includes(p.url));if(savedItems.length)persistProfileData()}saved=savedItems.map(p=>p.url);refreshProfileUi();$('savedCount').textContent=saved.length;$('emptyState').classList.add('hidden');$('results').classList.remove('hidden');render(papers);closeProfileModal();toast(`Switched to ${activeProfile.name}`)};refreshProfileUi();if(!activeProfile)openProfileModal();
refreshProfileUi=()=>{$('profileBtn').textContent=(activeProfile?.name||'Profile').slice(0,2).toUpperCase();$('profileTitle').textContent=activeProfile?`${activeProfile.name}'s profile`:'Create your profile';$('profileName').value=activeProfile?.name||'';$('profileSelect').innerHTML='<option value="">Create a new profile</option>'+profiles.map(p=>`<option value="${p.id}" ${p.id===activeProfileId?'selected':''}>${p.name}</option>`).join('');$('profileSave').textContent=activeProfile?'Save or switch':'Create profile'};
refreshProfileUi();$('profileSave').onclick=()=>{const selected=$('profileSelect').value;const typed=$('profileName').value.trim();if(selected&&selected===activeProfileId&&typed){activeProfile.name=typed;profiles=profiles.map(p=>p.id===activeProfileId?activeProfile:p)}else if(selected){activeProfileId=selected;activeProfile=profiles.find(p=>p.id===selected)}else if(typed){const id=typed.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||`profile-${Date.now()}`;activeProfile={id,name:typed};profiles=[...profiles,activeProfile];activeProfileId=id}else{return toast('Enter a profile name or choose an existing profile')}localStorage.setItem(profileStoreKey,JSON.stringify(profiles));localStorage.setItem(activeProfileKey,activeProfileId);savedItems=loadProfileData();saved=savedItems.map(p=>p.url);$('savedCount').textContent=saved.length;refreshProfileUi();closeProfileModal();render(papers);toast(`Profile updated: ${activeProfile.name}`)};


function profileHash(value){let h=2166136261;for(let i=0;i<value.length;i++)h=Math.imul(h^value.charCodeAt(i),16777619);return (h>>>0).toString(16)}
profiles=profiles.map(p=>({...p,passwordHash:p.passwordHash||''}));
refreshProfileUi=()=>{$('profileBtn').textContent=(activeProfile?.name||'Profile').slice(0,2).toUpperCase();$('profileTitle').textContent=activeProfile?(activeProfile.name+"'s profile"):'Create your profile';$('profileName').value=activeProfile?.name||'';$('profilePassword').value='';$('profileSelect').innerHTML='<option value="">Create a new profile</option>'+profiles.map(p=>'<option value="'+p.id+'" '+(p.id===activeProfileId?'selected':'')+'>'+p.name+'</option>').join('');$('profileSave').textContent=activeProfile?'Save or switch':'Create profile'};
refreshProfileUi();$('profileSave').onclick=()=>{const selected=$('profileSelect').value,name=$('profileName').value.trim(),password=$('profilePassword').value;if(password.length<4)return toast('Password must be at least 4 characters');if(selected&&selected===activeProfileId){activeProfile.name=name||activeProfile.name;activeProfile.passwordHash=profileHash(password);profiles=profiles.map(p=>p.id===activeProfileId?activeProfile:p)}else if(selected){const target=profiles.find(p=>p.id===selected);if(!target||target.passwordHash!==profileHash(password))return toast('Incorrect profile password');activeProfileId=selected;activeProfile=target}else if(name){const id=name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||('profile-'+Date.now());activeProfile={id,name,passwordHash:profileHash(password)};profiles=[...profiles,activeProfile];activeProfileId=id}else{return toast('Enter a profile name or choose an existing profile')}localStorage.setItem(profileStoreKey,JSON.stringify(profiles));localStorage.setItem(activeProfileKey,activeProfileId);savedItems=loadProfileData();saved=savedItems.map(p=>p.url);$('savedCount').textContent=saved.length;refreshProfileUi();closeProfileModal();render(papers);toast('Profile updated: '+activeProfile.name)};

$('profileDelete').onclick=()=>{const id=$('profileSelect').value||activeProfileId;const target=profiles.find(p=>p.id===id);const password=$('profilePassword').value;if(!target)return toast('No profile selected');if(target.passwordHash&&target.passwordHash!==profileHash(password))return toast('Incorrect profile password');if(!window.confirm('Delete '+target.name+' and all its saved papers?'))return;profiles=profiles.filter(p=>p.id!==id);localStorage.removeItem('papertrail-data-'+id);if(id===activeProfileId){activeProfile=profiles[0]||null;activeProfileId=activeProfile?.id||'';savedItems=loadProfileData();saved=savedItems.map(p=>p.url);localStorage.setItem(activeProfileKey,activeProfileId)}localStorage.setItem(profileStoreKey,JSON.stringify(profiles));refreshProfileUi();$('savedCount').textContent=saved.length;closeProfileModal();render(papers);toast('Profile deleted')};

// Sidebar close/open control
$('sidebarToggle').onclick=()=>{const shell=document.querySelector('.app-shell');const collapsed=shell.classList.toggle('sidebar-collapsed');$('sidebarToggle').textContent=collapsed?'Open menu':'Close menu'};
